version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - db
    environment:
      # Use DATABASE_URL for Elixir Phoenix applications
      DATABASE_URL: ecto://postgres:postgres@db/my_app_dev
      SECRET_KEY_BASE: YOUR_SECRET_KEY_BASE_HERE # Replace with a generated secret key
      MIX_ENV: dev
    ports:
      - "4000:4000"
      - "4001:4001" # For live reload
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: my_app_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
